# Generated by Django 2.2.4 on 2020-01-14 19:13

from django.db import migrations

def mark_buildings_old_or_new(apps, schema_editor):
	Flat = apps.get_model('property', 'Flat')
	for flat in Flat.objects.all():
		flat.new_building = flat.construction_year >= 2015
		flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
    migrations.RunPython(mark_buildings_old_or_new)
    ]
