# Generated by Django 2.2.4 on 2020-02-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(verbose_name='Текст обращения'),
        ),
    ]
