# Generated by Django 2.2.4 on 2020-02-23 20:22

from django.db import migrations

import phonenumbers


def parse_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_tel = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parsed_tel):
            flat.owner_phone_pure = phonenumbers.format_number(
                parsed_tel, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owner_phone_pure = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200223_2321'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumber)
    ]
