# Generated by Django 2.2.4 on 2020-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200224_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner',
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='ФИО владельца'),
            preserve_default=False,
        ),
    ]
