# Generated by Django 2.2.4 on 2020-02-24 11:26

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner, owners_phonenumber=flat.owners_phonenumber, owner_phone_pure=flat.owner_phone_pure)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200224_1426'),
    ]

    operations = [
        migrations.RunPython(create_owners)
    ]
